apiVersion: v1
kind: Service
metadata: 
  name: "wallet-service"
spec:
  selector:
    app: "wallet"
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
    nodePort: 30034
    name: wallet-server-port

