-- Add fee/audit fields to transaction (requested_amount, net_amount, fee_total, etc.)
-- Based on gateboxgo/database/create-table.sql

ALTER TABLE transaction ADD COLUMN IF NOT EXISTS requested_amount NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS net_amount NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS total_amount NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS fee_fixed NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS fee_percent_rate NUMERIC(16,4) DEFAULT 0.0000 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS fee_percent_amount NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS fee_total NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS ref_fee_fixed NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS ref_fee_percent_rate NUMERIC(16,4) DEFAULT 0.0000 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS ref_fee_percent_amount NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS ref_fee_total NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS gateway_fee NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS platform_fee NUMERIC(16,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS partner_fixed_cash_in NUMERIC(16,2) DEFAULT 0.00;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS partner_percent_cashin NUMERIC(16,4) DEFAULT 0.0000;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS fees_calculated_at TIMESTAMP;
ALTER TABLE transaction ADD COLUMN IF NOT EXISTS fee_calculation_version VARCHAR(20) DEFAULT 'v1.0';
