package transactionsRepo

var(
   SQL_TRANSACTIONS_LIST = `
       SELECT 
              id, 
              transaction_code, 
              wallet_id, 
              external_transaction_id, 
              id_transaction_type, 
              id_payment_method, 
              id_status, 
              amount, 
              id_currency, 
              fee_amount, 
              net_amount, 
              payer_user_id, 
              payer_wallet_id, 
              payee_user_id, 
              payee_wallet_id, 
              payee_external_account, 
              payment_method_id, 
              merchant_id, 
              merchant_name, 
              merchant_category, 
              device_id, 
              device_info, 
              location_data, 
              ip_address, 
              requires_signature, 
              signature_provided, 
              id_signature_method, 
              authorized_at, 
              completed_at, 
              cancelled_at, 
              description, 
              metadata, 
              created_at, 
              updated_at 
         FROM transactions
         ORDER BY id LIMIT $1 OFFSET $2
       ;`
 
   SQL_TRANSACTIONS_INSERT = `
       INSERT INTO transactions(
              transaction_code, 
              wallet_id, 
              external_transaction_id, 
              id_transaction_type, 
              id_payment_method, 
              id_status, 
              amount, 
              id_currency, 
              fee_amount, 
              net_amount, 
              payer_user_id, 
              payer_wallet_id, 
              payee_user_id, 
              payee_wallet_id, 
              payee_external_account, 
              payment_method_id, 
              merchant_id, 
              merchant_name, 
              merchant_category, 
              device_id, 
              device_info, 
              location_data, 
              ip_address, 
              requires_signature, 
              signature_provided, 
              id_signature_method, 
              authorized_at, 
              completed_at, 
              cancelled_at, 
              description, 
              metadata, 
              created_at, 
              updated_at) 
       VALUES( 
              $1, 
              $2, 
              $3, 
              $4, 
              $5, 
              $6, 
              $7, 
              $8, 
              $9, 
              $10, 
              $11, 
              $12, 
              $13, 
              $14, 
              $15, 
              $16, 
              $17, 
              $18, 
              $19, 
              $20, 
              $21, 
              $22, 
              $23, 
              $24, 
              $25, 
              $26, 
              $27, 
              $28, 
              $29, 
              $30, 
              $31, 
              $32, 
              $33) RETURNING id;` 

   SQL_TRANSACTIONS_UPDATE = `
       UPDATE transactions SET 
              transaction_code = $1, 
              wallet_id = $2, 
              external_transaction_id = $3, 
              id_transaction_type = $4, 
              id_payment_method = $5, 
              id_status = $6, 
              amount = $7, 
              id_currency = $8, 
              fee_amount = $9, 
              net_amount = $10, 
              payer_user_id = $11, 
              payer_wallet_id = $12, 
              payee_user_id = $13, 
              payee_wallet_id = $14, 
              payee_external_account = $15, 
              payment_method_id = $16, 
              merchant_id = $17, 
              merchant_name = $18, 
              merchant_category = $19, 
              device_id = $20, 
              device_info = $21, 
              location_data = $22, 
              ip_address = $23, 
              requires_signature = $24, 
              signature_provided = $25, 
              id_signature_method = $26, 
              authorized_at = $27, 
              completed_at = $28, 
              cancelled_at = $29, 
              description = $30, 
              metadata = $31, 
              created_at = $32, 
              updated_at = $33 
        WHERE id = $34; `

   SQL_TRANSACTIONS_DELETE_BY_ID = `
       DELETE FROM transactions
        WHERE id = $1; `

   SQL_GET_TRANSACTIONS_BY_ID = `
       SELECT 
              id, 
              transaction_code, 
              wallet_id, 
              external_transaction_id, 
              id_transaction_type, 
              id_payment_method, 
              id_status, 
              amount, 
              id_currency, 
              fee_amount, 
              net_amount, 
              payer_user_id, 
              payer_wallet_id, 
              payee_user_id, 
              payee_wallet_id, 
              payee_external_account, 
              payment_method_id, 
              merchant_id, 
              merchant_name, 
              merchant_category, 
              device_id, 
              device_info, 
              location_data, 
              ip_address, 
              requires_signature, 
              signature_provided, 
              id_signature_method, 
              authorized_at, 
              completed_at, 
              cancelled_at, 
              description, 
              metadata, 
              created_at, 
              updated_at 
         FROM transactions
        WHERE id = $1; `
 
   SQL_GET_TRANSACTIONS_BY_TRANSACTION_CODE = `
       SELECT 
              id, 
              transaction_code, 
              wallet_id, 
              external_transaction_id, 
              id_transaction_type, 
              id_payment_method, 
              id_status, 
              amount, 
              id_currency, 
              fee_amount, 
              net_amount, 
              payer_user_id, 
              payer_wallet_id, 
              payee_user_id, 
              payee_wallet_id, 
              payee_external_account, 
              payment_method_id, 
              merchant_id, 
              merchant_name, 
              merchant_category, 
              device_id, 
              device_info, 
              location_data, 
              ip_address, 
              requires_signature, 
              signature_provided, 
              id_signature_method, 
              authorized_at, 
              completed_at, 
              cancelled_at, 
              description, 
              metadata, 
              created_at, 
              updated_at 
         FROM transactions
        WHERE Transaction_code  LIKE '%' || $1 || '%' ; `
 
)